export const suratPerJuz = {
    1: [
        { id: 1, nama: "Al-Fatihah" },
        { id: 2, nama: "Al-Baqarah" },
    ],
    2: [{ id: 2, nama: "Al-Baqarah" }],
    3: [
        { id: 2, nama: "Al-Baqarah" },
        { id: 3, nama: "Ali 'Imran" },
    ],
    4: [
        { id: 3, nama: "Ali 'Imran" },
        { id: 4, nama: "An-Nisa" },
    ],
    5: [{ id: 4, nama: "An-Nisa" }],
    6: [
        { id: 4, nama: "An-Nisa" },
        { id: 5, nama: "Al-Ma'idah" },
    ],
    7: [
        { id: 5, nama: "Al-Ma'idah" },
        { id: 6, nama: "Al-An'am" },
    ],
    8: [
        { id: 6, nama: "Al-An'am" },
        { id: 7, nama: "Al-A'raf" },
    ],
    9: [
        { id: 7, nama: "Al-A'raf" },
        { id: 8, nama: "Al-Anfal" },
    ],
    10: [
        { id: 8, nama: "Al-Anfal" },
        { id: 9, nama: "At-Taubah" },
    ],
    11: [
        { id: 9, nama: "At-Taubah" },
        { id: 10, nama: "Yunus" },
        { id: 11, nama: "Hud" },
    ],
    12: [
        { id: 11, nama: "Hud" },
        { id: 12, nama: "Yusuf" },
    ],
    13: [
        { id: 12, nama: "Yusuf" },
        { id: 13, nama: "Ar-Ra'd" },
        { id: 14, nama: "Ibrahim" },
    ],
    14: [
        { id: 15, nama: "Al-Hijr" },
        { id: 16, nama: "An-Nahl" },
    ],
    15: [
        { id: 17, nama: "Al-Isra" },
        { id: 18, nama: "Al-Kahfi" },
    ],
    16: [
        { id: 18, nama: "Al-Kahfi" },
        { id: 19, nama: "Maryam" },
        { id: 20, nama: "Thaha" },
    ],
    17: [
        { id: 21, nama: "Al-Anbiya" },
        { id: 22, nama: "Al-Hajj" },
    ],
    18: [
        { id: 23, nama: "Al-Mu'minun" },
        { id: 24, nama: "An-Nur" },
        { id: 25, nama: "Al-Furqan" },
    ],
    19: [
        { id: 25, nama: "Al-Furqan" },
        { id: 26, nama: "Asy-Syu'ara" },
        { id: 27, nama: "An-Naml" },
    ],
    20: [
        { id: 27, nama: "An-Naml" },
        { id: 28, nama: "Al-Qasas" },
        { id: 29, nama: "Al-Ankabut" },
    ],
    21: [
        { id: 29, nama: "Al-Ankabut" },
        { id: 30, nama: "Ar-Rum" },
        { id: 31, nama: "Luqman" },
        { id: 32, nama: "As-Sajdah" },
        { id: 33, nama: "Al-Ahzab" },
    ],
    22: [
        { id: 33, nama: "Al-Ahzab" },
        { id: 34, nama: "Saba" },
        { id: 35, nama: "Fathir" },
        { id: 36, nama: "Yasin" },
    ],
    23: [
        { id: 36, nama: "Yasin" },
        { id: 37, nama: "As-Saffat" },
        { id: 38, nama: "Sad" },
        { id: 39, nama: "Az-Zumar" },
    ],
    24: [
        { id: 39, nama: "Az-Zumar" },
        { id: 40, nama: "Ghafir" },
        { id: 41, nama: "Fussilat" },
    ],
    25: [
        { id: 41, nama: "Fussilat" },
        { id: 42, nama: "Asy-Syura" },
        { id: 43, nama: "Az-Zukhruf" },
        { id: 44, nama: "Ad-Dukhan" },
        { id: 45, nama: "Al-Jatsiyah" },
    ],
    26: [
        { id: 46, nama: "Al-Ahqaf" },
        { id: 47, nama: "Muhammad" },
        { id: 48, nama: "Al-Fath" },
        { id: 49, nama: "Al-Hujurat" },
        { id: 50, nama: "Qaf" },
        { id: 51, nama: "Adz-Dzariyat" },
    ],
    27: [
        { id: 51, nama: "Adz-Dzariyat" },
        { id: 52, nama: "At-Tur" },
        { id: 53, nama: "An-Najm" },
        { id: 54, nama: "Al-Qamar" },
        { id: 55, nama: "Ar-Rahman" },
        { id: 56, nama: "Al-Waqi'ah" },
        { id: 57, nama: "Al-Hadid" },
    ],
    28: [
        { id: 58, nama: "Al-Mujadilah" },
        { id: 59, nama: "Al-Hasyr" },
        { id: 60, nama: "Al-Mumtahanah" },
        { id: 61, nama: "As-Saff" },
        { id: 62, nama: "Al-Jumu'ah" },
        { id: 63, nama: "Al-Munafiqun" },
        { id: 64, nama: "At-Taghabun" },
        { id: 65, nama: "At-Talaq" },
        { id: 66, nama: "At-Tahrim" },
    ],
    29: [
        { id: 67, nama: "Al-Mulk" },
        { id: 68, nama: "Al-Qalam" },
        { id: 69, nama: "Al-Haqqah" },
        { id: 70, nama: "Al-Ma'arij" },
        { id: 71, nama: "Nuh" },
        { id: 72, nama: "Al-Jinn" },
        { id: 73, nama: "Al-Muzzammil" },
        { id: 74, nama: "Al-Muddatstsir" },
        { id: 75, nama: "Al-Qiyamah" },
        { id: 76, nama: "Al-Insan" },
        { id: 77, nama: "Al-Mursalat" },
    ],
    30: [
        { id: 78, nama: "An-Naba" },
        { id: 79, nama: "An-Nazi'at" },
        { id: 80, nama: "'Abasa" },
        { id: 81, nama: "At-Takwir" },
        { id: 82, nama: "Al-Infitar" },
        { id: 83, nama: "Al-Muthaffifin" },
        { id: 84, nama: "Al-Insyiqaq" },
        { id: 85, nama: "Al-Buruj" },
        { id: 86, nama: "At-Tariq" },
        { id: 87, nama: "Al-A'la" },
        { id: 88, nama: "Al-Ghasyiyah" },
        { id: 89, nama: "Al-Fajr" },
        { id: 90, nama: "Al-Balad" },
        { id: 91, nama: "Asy-Syams" },
        { id: 92, nama: "Al-Lail" },
        { id: 93, nama: "Adh-Dhuha" },
        { id: 94, nama: "Al-Insyirah" },
        { id: 95, nama: "At-Tin" },
        { id: 96, nama: "Al-'Alaq" },
        { id: 97, nama: "Al-Qadr" },
        { id: 98, nama: "Al-Bayyinah" },
        { id: 99, nama: "Az-Zalzalah" },
        { id: 100, nama: "Al-'Adiyat" },
        { id: 101, nama: "Al-Qari'ah" },
        { id: 102, nama: "At-Takatsur" },
        { id: 103, nama: "Al-'Asr" },
        { id: 104, nama: "Al-Humazah" },
        { id: 105, nama: "Al-Fil" },
        { id: 106, nama: "Quraisy" },
        { id: 107, nama: "Al-Ma'un" },
        { id: 108, nama: "Al-Kautsar" },
        { id: 109, nama: "Al-Kafirun" },
        { id: 110, nama: "An-Nasr" },
        { id: 111, nama: "Al-Lahab" },
        { id: 112, nama: "Al-Ikhlas" },
        { id: 113, nama: "Al-Falaq" },
        { id: 114, nama: "An-Nas" },
    ],
};
